<center><i>
<font color="dodgerblue" style="font-family:cursive; font-size:18px;"><h1>TP 1 : NB / SVM / Neural Network</h1></font></i>
</center>
<hr>

[Lien Pour TP N°1 : Data Preparation (Google Colab)](https://colab.research.google.com/drive/1-oT7l5lkidI0VVRnKQ9oGPcykuVfs5pq?usp=sharing)

<h2><b><i><font color="tomato">I -Packages Importation:</font></i></b></h2>

<font style="font-family:cursive;">
<blockquote>
<i><font style="background-color:#ffabaf;"><b>pandas:</b></font>  est une bibliothèque écrite pour le langage de programmation Python permettant la manipulation et l'analyse des données. Elle propose en particulier des structures de données et des opérations de manipulation de tableaux numériques et de séries temporelles.</i>
<br/>
<br/>
<i><font style="background-color:#ffabaf;"><b>sklearn: </b></font>Scikit-learn est la principale bibliothèque d'outils dédiés au machine learning et à la data-science dans l'univers Python</i>
<blockquote>
    <i><font style="background-color:#ffabaf;"><b>train_test_split: </b></font>Dès que on a un apprentissage automatisé, Nous avon besoin de manipuler plusieurs ensembles. Nous allons découper l'ensemble labellisé en plusieurs sous-ensembles :</i><br/>
    <ul>
    <li><i>Un ensemble d'entraînement pour entraîner nos modèles de machine learning.</i></li>
    <li><i>Un ensemble de test pour mesurer la performance de nos modèles sur des données non apprises. La performance d'un modèle sur l'ensemble de test correspond à une mesure de ce modèle sur des données réelles, qui permettent d'évaluer la capacité de généralisation du modèle.</i></li>
    </ul>
    <i>Il est nécessaire que tous les ensembles que nous manipulons soient représentatifs du cas à modéliser sans quoi nous allons tester le modèle sur des données qui ne correspondent pas aux données d'entraînement. C'est pourquoi nous devons assurer que les distributions de tous ces ensembles sont comparables. Généralement on réalise des coupes aléatoires dans le dataset pour déterminer les sous-ensembles.</i>
    <br/><br/>
    <i><font style="background-color:#ffabaf;"><b>Naive Bayes:</b></font></i> La classification naïve bayésienne est un type de classification bayésienne probabiliste simple basée sur le théorème de Bayes avec une forte indépendance des hypothèses.
    <br/><br/>
    <i><font style="background-color:#ffabaf;"><b>SVM (Support Vector Machine ou Machine à vecteurs de support):</b></font> Les SVMs sont une famille d’algorithmes d‘apprentissage automatique qui permettent de résoudre des problèmes tant de classification que de régression ou de détection d’anomalie.</i>
    <br/><br/>
    <i><font style="background-color:#ffabaf;"><b>Les réseaux de neurones:</b></font> profonds représentent en réalité le dernier maillon dans l’évolution de l’intelligence artificielle. À l’origine, le Machine Learning permet d’automatiser les modèles statistiques par le biais d’algorithmes pour réaliser de meilleures prédictions.</i>
    <br/><br/>
   <i><font style="background-color:#ffabaf;"><b>metrics:</b></font> pour évaluer les performances de notre modéle.</i>
</blockquote>
    </blockquote>
       </font>

In [50]:
import pandas as pd # pandas is used to read files of the datasets
from sklearn.model_selection import train_test_split # train_test_split is used to part
from sklearn.naive_bayes import GaussianNB # GaussianNB() is the naive bayes classifier
from sklearn.svm import SVC # SVC() is the Support Vector Machines Classifier
from sklearn.neural_network import MLPClassifier # MLPClassifier us the Neural Network
from sklearn.metrics import confusion_matrix, classification_report # Confusion_matrix

In [51]:
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)

<h2><b><i><font color="tomato">II -Dataset Preparation:</font></i></b></h2>

In [52]:
df=pd.read_csv('bill_authentication.csv') # Read the dataset in a new data frame(df)
print("DataFrame's shape : ", df.shape)
df.head() # Display the first five rows (5 premières lignes)

DataFrame's shape :  (1372, 5)


Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [53]:
df.tail() # Display the last five rows (5 dernières lignes)

Variance  Skewness  Curtosis  Entropy  Class
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

<font style="font-family:cursive;"><i>Nous séparerons les échantillons et leurs classes.</i></font>

In [54]:
X=df.drop('Class',axis=1)
y=df['Class']
X.head()

Variance  Skewness  Curtosis  Entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [55]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [56]:
[X_train,X_test,y_train,y_test]=train_test_split(X,y,test_size=0.2)

In [57]:
print("Train dataset size: {}/{}".format(len(X_train),len(y)))
print("Test dataset size: {}/{}".format(len(X_test),len(y)))

Train dataset size: 1097/1372
Test dataset size: 275/1372


<h2><b><i><font color="tomato">III -Machine Learning: NB Vs SVM Vs Neural Network:</font></i></b></h2>

<i><h3><font style="font-family:cursive">Naive Bayes</font></h3></i>

In [58]:
gnb=GaussianNB() # gnb is a naive bayes classifier
gnb.fit(X_train,y_train) # Train Guassian NB classifier
y_nb=gnb.predict(X_test)

<i><h3><font style="font-family:cursive">SVM Lineair</font></h3></i>

In [59]:
linear_svm =SVC(kernel='linear') # linear_svm is a Linear Support Vectors
linear_svm.fit(X_train,y_train) # Train SVM
y_linear_svm=linear_svm.predict(X_test)

<i><h3><font style="font-family:cursive">Les autres algorithmes :</font></h3></i>

In [60]:
rbf_svm=SVC(kernel='rbf')# rbf_svm is a RBF support vectors
sigmoid_svm =SVC(kernel='sigmoid')# sigmoid support vectors
ploy_svm=SVC(kernel='poly',degree=2) # Ploynom with degree=2 as support vectors
neural=MLPClassifier(hidden_layer_sizes=(100,20),activation='relu',solver='adam') # neu

In [61]:
rbf_svm.fit(X_train,y_train)
sigmoid_svm.fit(X_train,y_train)
ploy_svm.fit(X_train,y_train)
neural.fit(X_train,y_train) # Train Neural Network - finding the best weight matrix

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 20), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [62]:
y_rbf_svm=rbf_svm.predict(X_test)
y_ploy_svm=ploy_svm.predict(X_test)
y_sigmoid_svm=sigmoid_svm.predict(X_test)
y_neural=neural.predict(X_test)

C:\Users\hadhemi\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:749: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = np.array(y > threshold, dtype=np.int)


<h2><b><i><font color="tomato">IV -Performance Evaluation:</font></i></b></h2>

In [63]:
print ('************* Peformance Evauation of Naive Bayes **************')
print(confusion_matrix(y_test,y_nb))
print(classification_report(y_test,y_nb))
print ('************* Peformance Evauation of Linear SVM **************')
print(confusion_matrix(y_test,y_linear_svm))
print(classification_report(y_test,y_linear_svm))
print ('************* Peformance Evauation of RBF SVM **************')
print(confusion_matrix(y_test,y_rbf_svm))
print(classification_report(y_test,y_rbf_svm))
print ('************* Peformance Evauation of Sigmoid SVM **************')
print(confusion_matrix(y_test,y_sigmoid_svm))
print(classification_report(y_test,y_sigmoid_svm))
print ('************* Peformance Evauation of Polynomial (2) SVM **************')
print(confusion_matrix(y_test,y_ploy_svm))
print(classification_report(y_test,y_ploy_svm))
print ('************* Peformance Evauation of Neural Network **************')
print(confusion_matrix(y_test,y_neural))
print(classification_report(y_test,y_neural))

************* Peformance Evauation of Naive Bayes **************
[[129  22]
 [ 28  96]]
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       151
           1       0.81      0.77      0.79       124

    accuracy                           0.82       275
   macro avg       0.82      0.81      0.82       275
weighted avg       0.82      0.82      0.82       275

************* Peformance Evauation of Linear SVM **************
[[148   3]
 [  2 122]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       151
           1       0.98      0.98      0.98       124

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

************* Peformance Evauation of RBF SVM **************
[[151   0]
 [  0 124]]
              precision    recall  f1-score   support

           0       1.00      1.0

<i><h4><font style="font-family:cursive">Nous choisissons SVM Linear car c'est le plus efficace pour nos Datasets.
</font></h3></i>